apiVersion: v1
kind: Service
metadata:
  name: {{ include "relaynet-internet-gateway.fullname" . }}-cogrpc
  labels:
    {{- include "relaynet-internet-gateway.labels" (merge (dict "Component" "cogrpc") .) | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: grpc
  selector:
    {{- include "relaynet-internet-gateway.selectorLabels" (merge (dict "Component" "cogrpc") .) | nindent 4 }}
