apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "relaynet-internet-gateway.fullname" . }}-cogrpc
data:
  GATEWAY_KEY_ID: {{ default .Values.gatewayKeyId (randAlphaNum 12 | b64enc) | quote }}
