apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "relaynet-internet-gateway.serviceAccountName" . }}-crcin
  labels:
    {{- include "relaynet-internet-gateway.labels" (merge (dict "Component" "crcin") .) | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
