{{- if .Values.ingress.enabled -}}
{{- $fullName :=  include "relaynet-internet-gateway.fullname" . -}}
apiVersion: {{ .Values.ingress.apiVersion }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "relaynet-internet-gateway.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.enableTls }}
  tls:
    - hosts:
      - {{ .Values.pohttpHost | quote }}
  {{- end }}
  rules:
    - host: {{ .Values.pohttpHost | quote }}
      http:
        paths:
          - backend:
              serviceName: {{ $fullName }}-pohttp
              servicePort: http
  {{- end }}
