name: "Syntax validation"
on:
  pull_request:
  push:
    branches: [master]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    # TODO: Delete?
    - name: Fetch history
      run: git fetch --prune --unshallow

    - name: Run chart-testing (lint)
      id: lint
      uses: helm/chart-testing-action@v1.0.0-rc.1
      with:
        command: lint
        config: /values.dev.yml

    - name: Create kind cluster
      uses: helm/kind-action@v1.0.0-rc.1

    - name: Run chart-testing (install)
      uses: helm/chart-testing-action@v1.0.0-rc.1
      with:
        command: install
        config: /values.dev.yml

#    - name: Set up Terraform
#      uses: volcano-coffee-company/setup-terraform@v1
#      with:
#        version: '~0.12'
#    - name: Validate Terraform example
#      run: |
#        cd example
#        terraform fmt -check
#        terraform init -backend=false
#        terraform validate
